### ISSUE TITLE
Question View Page

### ISSUE THREAD

**Issue by adwait-thattey** [adwait-thattey/ase1_prj#23]

**Comment by arminp17** [comment]
Dropdown for language select is not responsive.

**Comment by adwait-thattey** [comment]
@arminp17 Don't use the drpdown. Use the form select. Because the choice field will render as select element and not as button dropdown
[https://materializecss.com/select.html](https://materializecss.com/select.html)

**Comment by adwait-thattey** [comment]
@arminp17 BTW, it was not working, becoz jquery had not been included. I fixed it and pushed, but don't use dropdown

**Comment by arminp17** [comment]
Got it. 
BTW I am working on "questions/create" as you asked to merge it with "questions/view".

**Comment by arminp17** [comment]
@adwait-thattey Check the view question once, for any suggestions.
If fine, close the issue.
