### ISSUE TITLE
Come up with a cool name

### ISSUE THREAD

**Issue by adwait-thattey** [adwait-thattey/ase1_prj#29]
@all, please come with cool names for our websites.
Submit all your proposals in the comments below. 
After everyone has given their suggestions, we will have a poll and choose one of the names

**Comment by arminp17** [comment]
Code-House
Codinghub
Gradient coding

**Comment by Thoyiba** [comment]
Code It

**Comment by NikhilMunna** [comment]
Code champ,Tech champ,Code kick,Key to code,Code kit,Code cracker,Tech hunt,Codify

**Comment by NikhilMunna** [comment]
programista (programmer in filipino)

**Comment by NikhilMunna** [comment]
jammy programista(very lucky prograammer)
tyro programista (beginner programmer)
ken programista (knowledge programmer)

**Comment by adwait-thattey** [comment]
Code Cracker has been finalized
